# Generated by Django 4.2.30 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='luogu_pid',
            field=models.CharField(
                blank=True,
                help_text='洛谷题号，如 P1000',
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
    ]
