# Generated by Django 4.2.30 on 2026-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_time_limit_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True),
        ),
    ]
