# Generated by Django 5.2.15 on 2026-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_alter_testcase_input_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at'], 'verbose_name': '题目', 'verbose_name_plural': '题目'},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-created_at'], 'verbose_name': '官方题解', 'verbose_name_plural': '官方题解'},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['order', 'id'], 'verbose_name': '测试用例', 'verbose_name_plural': '测试用例'},
        ),
    ]
