# Generated by Django 5.2.15 on 2026-07-20 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_registration_points', models.PositiveIntegerField(default=0, help_text='通过邀请链接成功注册后，邀请人获得的积分。0 表示关闭奖励。', verbose_name='邀请人注册奖励积分')),
                ('invitee_registration_points', models.PositiveIntegerField(default=0, help_text='通过邀请链接成功注册后，新用户获得的积分。0 表示关闭奖励。', verbose_name='受邀人注册奖励积分')),
                ('accepted_testcase_points', models.PositiveIntegerField(default=0, help_text='普通题目中，用户首次通过某个非样例测试点时获得的积分。', verbose_name='AC 测试点奖励积分')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '积分配置',
                'verbose_name_plural': '积分配置',
            },
        ),
        migrations.CreateModel(
            name='PointLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='积分变动')),
                ('balance_after', models.IntegerField(verbose_name='变动后余额')),
                ('event_type', models.CharField(max_length=50, verbose_name='事件类型')),
                ('event_key', models.CharField(max_length=200, verbose_name='事件键')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '积分流水',
                'verbose_name_plural': '积分流水',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type', 'event_key'), name='unique_user_point_event')],
            },
        ),
    ]
