# Generated by Django 5.2.15 on 2026-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointconfig',
            name='accepted_testcase_points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='普通题目中，用户首次通过某个非样例测试点时获得的积分，最多保留两位小数。', max_digits=12, verbose_name='AC 测试点奖励积分'),
        ),
        migrations.AlterField(
            model_name='pointledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='积分变动'),
        ),
        migrations.AlterField(
            model_name='pointledgerentry',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='变动后余额'),
        ),
    ]
