# Generated by Django 5.2.15 on 2026-07-20 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_alter_pointconfig_accepted_testcase_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointconfig',
            name='accepted_testcase_points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='普通题目中，用户首次通过某个非样例测试点时获得的积分，最多保留两位小数。', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='AC 测试点奖励积分'),
        ),
    ]
