# Generated by Django 4.2.30 on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solved_problems',
            field=models.ManyToManyField(blank=True, related_name='solved_by', to='problems.problem'),
        ),
    ]
