# Generated by Django 4.2.30 on 2026-05-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
        ('users', '0002_user_solved_problems'),
    ]

    operations = [
    ]
