# Generated by Django 6.0.6 on 2026-06-06 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=64)),
                ('data', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_blob', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
