# Generated by Django 5.2.15 on 2026-07-04 02:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned_reason',
            field=models.CharField(blank=True, max_length=300, verbose_name='封号原因'),
        ),
        migrations.AddField(
            model_name='user',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='临时封号截止时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='disabled_features',
            field=models.TextField(blank=True, default='', verbose_name='禁用功能列表'),
        ),
        migrations.AddField(
            model_name='user',
            name='disabled_features_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='功能禁用截止时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_permanently_banned',
            field=models.BooleanField(default=False, verbose_name='永久封号'),
        ),
        migrations.CreateModel(
            name='IpBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP 封禁',
                'verbose_name_plural': 'IP 封禁',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPunishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punishment_type', models.CharField(choices=[('permanent_ban', '永久封号'), ('temp_ban', '临时封号'), ('feature_ban', '禁用某些功能'), ('warning', '警告')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_features', models.CharField(blank=True, default='', max_length=300)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punishments_issued', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punishments_revoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户处罚记录',
                'verbose_name_plural': '用户处罚记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
