# Generated by Django 5.2.15 on 2026-07-15 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_banned_reason_user_banned_until_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
