# Generated by Django 5.2.15 on 2026-07-20 03:48

import secrets

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_referral_codes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    for user in User.objects.filter(referral_code='').iterator():
        while True:
            candidate = secrets.token_urlsafe(8)[:12]
            if not User.objects.filter(referral_code=candidate).exists():
                User.objects.filter(pk=user.pk).update(referral_code=candidate)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_last_login_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_balance',
            field=models.IntegerField(default=0, verbose_name='积分余额'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='邀请码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='邀请人'),
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=16, unique=True, verbose_name='邀请码'),
        ),
    ]
