# Generated by Django 5.2.15 on 2026-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_points_balance_user_referral_code_user_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='积分余额'),
        ),
    ]
