# Generated by Django 5.2.15 on 2026-07-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_points_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='积分余额'),
        ),
    ]
