# Generated by Django 4.2.30 on 2026-05-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submissiontestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontestresult',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Skipped', 'Skipped')], max_length=30),
        ),
    ]
