# Generated by Django 6.0.6 on 2026-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_alter_submissiontestresult_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('Assembly', 'Assembly'), ('Rust', 'Rust'), ('Golang', 'Golang')], max_length=10),
        ),
    ]
