# Generated by Django 6.0.6 on 2026-06-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.IntegerField(default=6379)),
                ('db', models.IntegerField(default=0)),
                ('queue', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('weight', models.IntegerField(default=1, help_text='Higher weight = more tasks')),
            ],
            options={
                'verbose_name': 'Judge Machine',
                'verbose_name_plural': 'Judge Machines',
                'ordering': ['name'],
            },
        ),
    ]
