# Generated by Django 5.2.15 on 2026-06-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_judgemachine'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprocess_timeout_sec', models.IntegerField(default=5, help_text='Global subprocess timeout in seconds (safety net for all executions)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Judge Configuration',
                'verbose_name_plural': 'Judge Configuration',
            },
        ),
    ]
