# Generated by Django 5.2.15 on 2026-07-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_judgeconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judgeconfig',
            options={'verbose_name': '评测配置', 'verbose_name_plural': '评测配置'},
        ),
        migrations.AlterModelOptions(
            name='judgemachine',
            options={'ordering': ['name'], 'verbose_name': '评测机', 'verbose_name_plural': '评测机'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at'], 'verbose_name': '提交记录', 'verbose_name_plural': '提交记录'},
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('TypeScript', 'TypeScript'), ('Golang', 'Golang'), ('Rust', 'Rust'), ('Ruby', 'Ruby'), ('Kotlin', 'Kotlin'), ('Assembly', 'Assembly')], max_length=32),
        ),
    ]
