# Generated by Django 5.2.15 on 2026-07-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_alter_judgeconfig_options_alter_judgemachine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('Golang', 'Golang'), ('Rust', 'Rust'), ('Ruby', 'Ruby'), ('Kotlin', 'Kotlin'), ('Assembly', 'Assembly')], max_length=32),
        ),
    ]
