# Generated by Django 5.2.15 on 2026-07-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('submissions', '0009_submission_system_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='contest_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='contests.contestproblem'),
        ),
    ]
