# Generated by Django 5.2.15 on 2026-07-17 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_standalone_contest_problem_schema'),
        ('problems', '0007_alter_problem_options_alter_solution_options_and_more'),
        ('submissions', '0012_add_contest_test_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'created_at'], name='submissions_status_75026c_idx'),
        ),
    ]
