# Generated by Django 5.2.15 on 2026-07-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0013_pending_submission_deadline_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='judge_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
