# Generated by Django 5.2.15 on 2026-07-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0014_submission_judge_started_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='submission',
            name='submissions_status_75026c_idx',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='judge_started_at',
        ),
    ]
