# Generated by Django 5.2.15 on 2026-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0015_remove_submission_submissions_status_75026c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgemachine',
            name='ca_cert_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='judgemachine',
            name='client_cert_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='judgemachine',
            name='client_key_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='judgemachine',
            name='redis_password_encrypted',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='judgemachine',
            name='tls_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judgemachine',
            name='transport_configured',
            field=models.BooleanField(default=False, help_text='Use the TLS/password settings below instead of JUDGE_MACHINES_JSON defaults.'),
        ),
    ]
