# Generated by Django 6.0.8 on 2026-09-11 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0007_alter_problem_options_alter_solution_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plus_product_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Plus Product ID')),
                ('pro_product_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Pro Product ID')),
                ('plus_monthly_price_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Plus 月付 Price ID')),
                ('plus_yearly_price_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Plus 年付 Price ID')),
                ('pro_monthly_price_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Pro 月付 Price ID')),
                ('pro_yearly_price_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Pro 年付 Price ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '订阅计费配置',
                'verbose_name_plural': '订阅计费配置',
            },
        ),
        migrations.CreateModel(
            name='AISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', '进行中'), ('satisfied', '已采纳')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 解题会话',
                'verbose_name_plural': 'AI 解题会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveSmallIntegerField(default=1, verbose_name='轮次')),
                ('prompt', models.TextField(verbose_name='发送给模型的提示词')),
                ('answer', models.TextField(blank=True, default='', verbose_name='模型回答')),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_message', models.CharField(blank=True, default='', max_length=300, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='ai_assistant.aisession')),
            ],
            options={
                'verbose_name': 'AI 生成记录',
                'verbose_name_plural': 'AI 生成记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', '免费版'), ('plus', 'Plus 会员'), ('pro', 'Pro 会员')], default='free', max_length=16, verbose_name='套餐')),
                ('status', models.CharField(choices=[('active', '生效中'), ('canceled', '已取消')], default='active', max_length=16, verbose_name='状态')),
                ('interval', models.CharField(blank=True, default='', max_length=8, verbose_name='计费周期')),
                ('stripe_customer_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Stripe Subscription ID')),
                ('current_period_start', models.DateTimeField(blank=True, null=True, verbose_name='当前周期开始')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='当前周期结束')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='周期结束后取消')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 订阅',
                'verbose_name_plural': 'AI 订阅',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aisession',
            index=models.Index(fields=['user', 'problem', '-created_at'], name='ai_assistan_user_id_2cac66_idx'),
        ),
        migrations.AddIndex(
            model_name='aigeneration',
            index=models.Index(fields=['user', 'success', '-created_at'], name='ai_assistan_user_id_894cf4_idx'),
        ),
    ]
