# Generated by Django 6.0.8 on 2026-09-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneration',
            name='reasoning',
            field=models.TextField(blank=True, default='', verbose_name='模型思考过程'),
        ),
    ]
