# Generated by Django 5.2.15 on 2026-07-04 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('health_cache_seconds', models.IntegerField(default=1800, help_text='status_page 读取健康检查结果时的缓存 TTL；设为 0 表示每次访问都重新探测（不推荐）。', verbose_name='健康检查结果缓存(秒)')),
                ('github_cache_seconds', models.IntegerField(default=7200, help_text='GitHub 提交列表在缓存中保留的秒数。', verbose_name='GitHub 提交记录缓存(秒)')),
            ],
            options={
                'verbose_name': '缓存配置',
                'verbose_name_plural': '缓存配置',
            },
        ),
        migrations.CreateModel(
            name='FileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('file_hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('mtime', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件快照',
                'verbose_name_plural': '文件快照',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='HealthCheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('uptime_window_days', models.IntegerField(default=90, help_text='ServiceComponent.uptime_90_days 使用的窗口大小。', verbose_name='可用率滑动窗口(天)')),
                ('sample_retention_days', models.IntegerField(default=97, help_text='超过该天数的 HealthSample 行将在每次健康检查后被清理。', verbose_name='健康检查样本保留天数')),
                ('judge_max_wait_seconds', models.IntegerField(default=15, help_text='提交 A+B 健康用例后最多等待的秒数；超时视为该样本失败。', verbose_name='评测系统探测最长等待(秒)')),
                ('judge_pass_score', models.IntegerField(default=3, help_text='健康用例通过数 ≥ 该值时该次 sample 记为 OK。', verbose_name='评测系统健康阈值(通过用例数)')),
                ('judge_score_degraded', models.IntegerField(default=2, help_text='score == 该值 时组件状态显示为"性能下降"。', verbose_name='评测系统状态-性能下降阈值')),
                ('judge_score_partial', models.IntegerField(default=1, help_text='score == 该值 时组件状态显示为"部分中断"。', verbose_name='评测系统状态-部分中断阈值')),
                ('file_change_days', models.IntegerField(default=30, help_text='status_page 变更列表中仅展示最近 N 天内的变更。', verbose_name='文件变更展示窗口(天)')),
                ('health_alert_enabled', models.BooleanField(default=True, help_text='关闭后 _send_health_alert 不发送任何邮件，但仍记录 sample。', verbose_name='启用健康告警邮件')),
            ],
            options={
                'verbose_name': '健康检查配置',
                'verbose_name_plural': '健康检查配置',
            },
        ),
        migrations.CreateModel(
            name='RegistrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('email_verification_required', models.BooleanField(default=True, help_text='关闭后，注册表单不再要求填写 6 位邮箱验证码。', verbose_name='注册需邮箱验证')),
                ('verification_code_ttl_seconds', models.IntegerField(default=600, help_text='邮箱验证码在 Redis 中的 TTL。默认 10 分钟。', verbose_name='验证码有效期(秒)')),
                ('verification_code_length', models.IntegerField(default=6, help_text='发送给用户的邮箱验证码位数，应与表单中 1–1 对应。', verbose_name='验证码长度')),
                ('verification_rate_limit_per_hour', models.IntegerField(default=5, help_text='单个邮箱每小时最多可请求发送验证码的次数。', verbose_name='每邮箱每小时最多发送次数')),
                ('registration_enabled', models.BooleanField(default=True, help_text='关闭后，全站关闭所有用户注册入口。', verbose_name='允许注册')),
            ],
            options={
                'verbose_name': '注册配置',
                'verbose_name_plural': '注册配置',
            },
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名')),
                ('status', models.CharField(choices=[('operational', '正常运作'), ('degraded', '性能下降'), ('partial', '部分中断'), ('major', '重大中断'), ('maintenance', '维护中')], default='operational', max_length=20, verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('uptime', models.FloatField(blank=True, default=100.0, verbose_name='90 天可用率(%)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('auto_check', models.BooleanField(default=False, verbose_name='自动健康检查')),
                ('health_key', models.CharField(blank=True, help_text='对应 /health/ 返回的 checks 键，如 database / redis / cache', max_length=50, verbose_name='健康检查项')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务组件',
                'verbose_name_plural': '服务组件',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='内容(Markdown)')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devlog_entries', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '开发者日志',
                'verbose_name_plural': '开发者日志',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('change_type', models.CharField(choices=[('added', '新增'), ('modified', '修改'), ('deleted', '删除')], max_length=10, verbose_name='变更类型')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('old_hash', models.CharField(blank=True, max_length=64)),
                ('size', models.BigIntegerField(default=0, verbose_name='大小(字节)')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_changes', to=settings.AUTH_USER_MODEL, verbose_name='备注人')),
            ],
            options={
                'verbose_name': '文件改动',
                'verbose_name_plural': '文件改动',
                'ordering': ['-detected_at', 'path'],
                'indexes': [models.Index(fields=['-detected_at'], name='devlog_file_detecte_e7fe6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False, null=True, verbose_name='是否通过')),
                ('score', models.IntegerField(default=0, verbose_name='评分 / 通过用例数')),
                ('sampled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='采样时间')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_samples', to='devlog.servicecomponent', verbose_name='服务组件')),
            ],
            options={
                'verbose_name': '健康检查采样',
                'verbose_name_plural': '健康检查采样',
                'ordering': ['-sampled_at'],
                'indexes': [models.Index(fields=['component', '-sampled_at'], name='devlog_heal_compone_a70626_idx')],
            },
        ),
    ]
