# Generated by Django 5.2.15 on 2026-06-14 03:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, unique=True)),
                ('file_hash', models.CharField(max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('mtime', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文件快照',
                'verbose_name_plural': '文件快照',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='ServiceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名')),
                ('status', models.CharField(choices=[('operational', '正常运作'), ('degraded', '性能下降'), ('partial', '部分中断'), ('major', '重大中断'), ('maintenance', '维护中')], default='operational', max_length=20, verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='说明')),
                ('uptime', models.FloatField(default=100.0, verbose_name='90 天可用率(%)')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('auto_check', models.BooleanField(default=False, verbose_name='自动健康检查')),
                ('health_key', models.CharField(blank=True, help_text='对应 /health/ 返回的 checks 键，如 database / redis / cache', max_length=50, verbose_name='健康检查项')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务组件',
                'verbose_name_plural': '服务组件',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=40, verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('body', models.TextField(blank=True, verbose_name='内容(Markdown)')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devlog_entries', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '开发者日志',
                'verbose_name_plural': '开发者日志',
                'ordering': ['-pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('change_type', models.CharField(choices=[('added', '新增'), ('modified', '修改'), ('deleted', '删除')], max_length=10, verbose_name='变更类型')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('old_hash', models.CharField(blank=True, max_length=64)),
                ('size', models.BigIntegerField(default=0, verbose_name='大小(字节)')),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检测时间')),
                ('remarks', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotated_changes', to=settings.AUTH_USER_MODEL, verbose_name='备注人')),
            ],
            options={
                'verbose_name': '文件改动',
                'verbose_name_plural': '文件改动',
                'ordering': ['-detected_at', 'path'],
                'indexes': [models.Index(fields=['-detected_at'], name='devlog_file_detecte_e7fe6b_idx')],
            },
        ),
    ]
