# Generated by Django 5.2.15 on 2026-07-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheconfig',
            name='page_cache_seconds',
            field=models.IntegerField(default=900, help_text='整页 cache_page 的默认保留时间，在各个视图可以独立配置后生效。', verbose_name='页面缓存默认 TTL(秒)'),
        ),
    ]
