# Generated by Django 5.2.15 on 2026-07-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0002_cacheconfig_page_cache_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_on_register', models.BooleanField(default=True, verbose_name='注册时要求验证码')),
                ('captcha_on_login_after_failures', models.PositiveSmallIntegerField(default=1, help_text='同一 IP 登录失败 N 次后强制要求图形验证码', verbose_name='登录失败次数后要求验证码')),
                ('captcha_answer_length', models.PositiveSmallIntegerField(default=5, verbose_name='验证码长度')),
                ('captcha_challenge_ttl_seconds', models.IntegerField(default=600, verbose_name='验证码有效时间(秒)')),
                ('captcha_per_ip_per_minute', models.PositiveSmallIntegerField(default=20, verbose_name='每 IP 每分钟最多生成次数')),
                ('captcha_attempts_per_ip_per_10_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='每 IP 每 10 分钟最多验证次数')),
                ('captcha_require_on_forgot_password', models.BooleanField(default=True, verbose_name='忘记密码时要求验证码')),
                ('captcha_require_on_all_post', models.BooleanField(default=False, help_text='开启后，发帖 / 评论 / 提交题目等所有 POST 请求都会检查是否携带 captcha_id/answer；用于高风险时期', verbose_name='所有 POST 操作都要求验证码')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '验证码配置',
                'verbose_name_plural': '验证码配置',
            },
        ),
        migrations.AlterField(
            model_name='cacheconfig',
            name='github_cache_seconds',
            field=models.IntegerField(default=7200, help_text='GitHub 提交列表在缓存中保留的秒数', verbose_name='GitHub 提交记录缓存(秒)'),
        ),
        migrations.AlterField(
            model_name='cacheconfig',
            name='health_cache_seconds',
            field=models.IntegerField(default=1800, help_text='status_page 读取健康检查结果时的缓存 TTL', verbose_name='健康检查结果缓存(秒)'),
        ),
        migrations.AlterField(
            model_name='cacheconfig',
            name='page_cache_seconds',
            field=models.IntegerField(default=900, help_text='整页 cache_page 的默认保留时间', verbose_name='页面缓存默认 TTL(秒)'),
        ),
    ]
