# Generated by Django 5.2.15 on 2026-07-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0003_captchaconfig_alter_cacheconfig_github_cache_seconds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='生产环境用 smtp；调试可用 django.core.mail.backends.console.EmailBackend 把邮件打印到日志', max_length=120, verbose_name='Email Backend')),
                ('email_host', models.CharField(default='smtp.example.com', max_length=120, verbose_name='SMTP 服务器地址')),
                ('email_port', models.PositiveIntegerField(default=587, help_text='TLS 常用 587；SSL 常用 465；未加密常用 25', verbose_name='SMTP 端口')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='使用 STARTTLS (端口 587)')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='使用 SSL (端口 465)')),
                ('email_host_user', models.CharField(blank=True, default='', help_text='例如 noreply@your-domain.com', max_length=120, verbose_name='SMTP 用户名')),
                ('email_host_password', models.CharField(blank=True, default='', help_text='QQ/163 等邮箱通常使用“授权码”而不是登录密码', max_length=200, verbose_name='SMTP 密码 / 授权码')),
                ('default_from_email', models.CharField(blank=True, default='', help_text='例如 "Guwu OJ <noreply@your-domain.com>"。留空则使用 SMTP 用户名', max_length=200, verbose_name='默认发件人')),
                ('email_timeout', models.PositiveSmallIntegerField(default=20, verbose_name='单次发送超时(秒)')),
                ('admin_recipients', models.TextField(blank=True, default='', help_text='健康告警等系统邮件的收件人，每行一个邮箱', verbose_name='管理员收件人列表')),
                ('site_name_for_email', models.CharField(blank=True, default='Guwu Online Judge', max_length=80, verbose_name='邮件中显示的站点名')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
            },
        ),
    ]
