# Generated by Django 5.2.15 on 2026-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0004_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaconfig',
            name='captcha_submission_captcha_enabled',
            field=models.BooleanField(default=True, help_text='当用户在时间窗口内提交超过阈值时，必须先输入图形验证码才能继续提交', verbose_name='高频提交时要求验证码'),
        ),
        migrations.AddField(
            model_name='captchaconfig',
            name='captcha_submission_limit',
            field=models.PositiveSmallIntegerField(default=10, help_text='在时间窗口内提交次数超过该值后强制要求图形验证码', verbose_name='验证码触发阈值（次数）'),
        ),
        migrations.AddField(
            model_name='captchaconfig',
            name='captcha_submission_window_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='统计提交频率的时间窗口长度，修改后立即生效', verbose_name='验证码触发窗口（分钟）'),
        ),
    ]
