# Generated by Django 5.2.15 on 2026-07-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0007_siteconfig_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.AlterField(
            model_name='healthcheckconfig',
            name='sample_retention_days',
            field=models.IntegerField(default=37, help_text='超过该天数的 HealthSample 行将在每次健康检查后被清理。', verbose_name='健康检查样本保留天数'),
        ),
        migrations.AlterField(
            model_name='healthcheckconfig',
            name='uptime_window_days',
            field=models.IntegerField(default=30, help_text='ServiceComponent.uptime_90_days 使用的窗口大小。', verbose_name='可用率滑动窗口(天)'),
        ),
        migrations.AlterField(
            model_name='servicecomponent',
            name='uptime',
            field=models.FloatField(blank=True, default=100.0, verbose_name='可用率(%)'),
        ),
    ]
