# Generated by Django 5.2.15 on 2026-07-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0008_delete_siteconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('monaco_source', models.CharField(choices=[('jsdelivr', 'jsDelivr CDN（默认，全球较快）'), ('unpkg', 'unpkg CDN（npm 直连）'), ('cdnjs', 'cdnjs CDN'), ('bootcdn', 'BootCDN（国内较快）'), ('custom', '自定义地址（下方填写完整 URL 前缀）')], default='jsdelivr', help_text='切换提交页代码编辑器的 CDN 源；修改后立即生效（下一次打开页面）', max_length=20, verbose_name='Monaco 加载源')),
                ('monaco_custom_base', models.CharField(blank=True, default='', help_text='指向 /min/vs 目录（不含结尾斜杠）', max_length=500, verbose_name='自定义 Monaco 基础 URL（仅当上方选择"自定义地址"时使用）')),
                ('monaco_version', models.CharField(default='0.52.2', help_text='一般保持默认即可；修改前请确认目标 CDN 存在该版本', max_length=30, verbose_name='Monaco 版本号')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
