# Generated by Django 5.2.15 on 2026-07-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0009_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='bootstrap_css_version',
            field=models.CharField(default='5.3.0', help_text='例如 5.3.0；修改前请确认目标 CDN 存在该版本', max_length=30, verbose_name='Bootstrap 主版本号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bootstrap_custom_css',
            field=models.CharField(blank=True, default='', help_text='仅当上方选择"自定义地址"时使用；留空则退回到 jsDelivr', max_length=500, verbose_name='自定义 Bootstrap CSS URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bootstrap_custom_icons',
            field=models.CharField(blank=True, default='', help_text='仅当上方选择"自定义地址"时使用；留空则退回到 jsDelivr', max_length=500, verbose_name='自定义 Bootstrap Icons CSS URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bootstrap_custom_js',
            field=models.CharField(blank=True, default='', help_text='仅当上方选择"自定义地址"时使用；留空则退回到 jsDelivr', max_length=500, verbose_name='自定义 Bootstrap JS bundle URL'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bootstrap_icons_version',
            field=models.CharField(default='1.10.0', help_text='例如 1.10.0', max_length=30, verbose_name='Bootstrap Icons 版本号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='bootstrap_source',
            field=models.CharField(choices=[('jsdelivr', 'jsDelivr CDN（默认，全球较快）'), ('unpkg', 'unpkg CDN（npm 直连）'), ('cdnjs', 'cdnjs CDN'), ('bootcdn', 'BootCDN（国内较快）'), ('custom', '自定义地址（下方填写）')], default='jsdelivr', help_text='切换前端页面（提交页/主页等）使用的 Bootstrap 源', max_length=20, verbose_name='Bootstrap 加载源'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='static_cache_ttl_seconds',
            field=models.IntegerField(default=86400, help_text='设置白噪声对 /static/ 文件的 Cache-Control max-age；默认 1 天', verbose_name='静态文件 /static/ 缓存 TTL（秒）'),
        ),
    ]
