# Generated by Django 5.2.15 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0010_siteconfig_bootstrap_css_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaconfig',
            name='captcha_avatar_captcha_enabled',
            field=models.BooleanField(
                default=True,
                help_text='当同一 IP 在时间窗口内请求头像达到阈值时，要求完成图形验证码。',
                verbose_name='头像高频访问时要求验证码',
            ),
        ),
        migrations.AddField(
            model_name='captchaconfig',
            name='captcha_avatar_request_limit',
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text='同一 IP 在窗口内请求头像达到该次数后要求图形验证码。',
                verbose_name='头像验证码触发阈值（次数）',
            ),
        ),
        migrations.AddField(
            model_name='captchaconfig',
            name='captcha_avatar_request_window_minutes',
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text='统计同一 IP 头像请求次数的时间窗口长度。',
                verbose_name='头像验证码触发窗口（分钟）',
            ),
        ),
    ]
