# Generated by Django 5.2.15 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0011_captchaconfig_avatar_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('page_views', models.PositiveBigIntegerField(default=0, verbose_name='页面访问量')),
            ],
            options={
                'verbose_name': '每日流量',
                'verbose_name_plural': '每日流量',
                'ordering': ['-day'],
            },
        ),
    ]
