# Generated by Django 5.2.15 on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0012_trafficdailymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficPageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='日期')),
                ('path', models.CharField(max_length=200, verbose_name='页面路径')),
                ('page_views', models.PositiveBigIntegerField(default=0, verbose_name='页面访问量')),
            ],
            options={
                'verbose_name': '每日页面流量',
                'verbose_name_plural': '每日页面流量',
                'ordering': ['-day', 'path'],
                'indexes': [models.Index(fields=['day', 'path'], name='devlog_traf_day_ca519f_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'path'), name='unique_traffic_page_day')],
            },
        ),
    ]
