# Generated by Django 6.0.7 on 2026-07-24 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0015_rename_devlog_traf_day_8b7f8a_idx_devlog_traf_day_5263c3_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrafficMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='匿名会话')),
                ('hour', models.DateTimeField(db_index=True, verbose_name='小时')),
                ('path', models.CharField(max_length=200, verbose_name='页面路径')),
                ('page_views', models.PositiveBigIntegerField(default=0, verbose_name='访问次数')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_metrics', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户浏览流量',
                'verbose_name_plural': '用户浏览流量',
                'indexes': [models.Index(fields=['user', 'hour'], name='devlog_user_user_id_95aeb9_idx'), models.Index(fields=['session_key', 'hour'], name='devlog_user_session_af004e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'hour', 'path'), name='unique_user_traffic_hour_path'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'hour', 'path'), name='unique_session_traffic_hour_path')],
            },
        ),
    ]

# Migration files are normally ignored by this repository's global pattern;
# force-add this file when deploying analytics.
