# Generated by Django 6.0.7 on 2026-07-24 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0016_usertrafficmetric'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usertrafficmetric',
            new_name='devlog_user_user_id_2111f7_idx',
            old_name='devlog_user_user_id_95aeb9_idx',
        ),
        migrations.RenameIndex(
            model_name='usertrafficmetric',
            new_name='devlog_user_session_d7c1e6_idx',
            old_name='devlog_user_session_af004e_idx',
        ),
    ]
