# Generated by Django 6.0.7 on 2026-07-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('devlog', '0017_rename_devlog_user_user_id_95aeb9_idx_devlog_user_user_id_2111f7_idx_and_more')]
    operations = [
        migrations.CreateModel(
            name='TrafficBrowserLocationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True, verbose_name='日期')),
                ('latitude', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='粗略纬度')),
                ('longitude', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='粗略经度')),
                ('requests', models.PositiveBigIntegerField(default=0, verbose_name='请求数')),
            ],
            options={'verbose_name': '浏览器位置流量', 'verbose_name_plural': '浏览器位置流量', 'indexes': [models.Index(fields=['day', 'latitude', 'longitude'], name='devlog_tra_day_lat_long_idx')], 'constraints': [models.UniqueConstraint(fields=('day', 'latitude', 'longitude'), name='unique_browser_location_day_point')]},
        ),
    ]

# Force-add this migration when deploying because the repository ignores migrations globally.
