# Generated by Django 6.0.7 on 2026-07-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0018_trafficbrowserlocationmetric'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trafficbrowserlocationmetric',
            new_name='devlog_traf_day_160530_idx',
            old_name='devlog_tra_day_lat_long_idx',
        ),
    ]
