# Generated by Django 5.2.15 on 2026-07-20 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_standalone_contest_problem_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='entry_points_cost',
            field=models.PositiveIntegerField(default=50, verbose_name='参加消耗积分'),
        ),
        migrations.CreateModel(
            name='ContestEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_cost', models.PositiveIntegerField(verbose_name='实际消耗积分')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='contests.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '竞赛报名',
                'verbose_name_plural': '竞赛报名',
                'constraints': [models.UniqueConstraint(fields=('contest', 'user'), name='unique_contest_enrollment')],
            },
        ),
    ]
